use distro package
installing from pip would require extra dev packages:

Modules/errors.h:8:18: fatal error: lber.h: No such file or directory
     #include "lber.h"